# SITE SETUP
#config/params.yaml
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: dark
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: "Personal website of Ashraf Hany — AI & Data Engineer, researcher in deep learning, computer vision, and quantum machine learning. First Class Honours BSc, MSA University & University of Greenwich."
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: 'xmBSew_uKO_u7cEQczXCIRUnCvokVaFYQeOArvFVESs'
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: false
    logo:
      text: ""

# Site footer
footer:
  copyright:
    notice: 'Per Aspera Ad Astra'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  comment:
    provider: disqus
    disqus:
      shortname: 'https-ashrafhanyy-github-io-blog'
design:
  blog_post:
    full_width: true